
name: Yancy (Yang) Li
description: Break Through Straightforwardly
url: 
baseurl: 



avatar: https://i.postimg.cc/L6mQt7hq/mmexport1622094428095.jpg

favicon: https://i.postimg.cc/cCfHdCfJ/image.png


navigation:
  - name: About Me
    url: /about
  - name: Blogs
    url: /archive
  - name: Tags
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links: 
  weibo:  #https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: liyang.sufe@gmail.com #youremailaddress@mail.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: YancyLi1117 #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>


footer-text: Copyright (c) 2022 from Waterloo

#
# 评论，注意，请不要同时添加多种不同的评论区
#

# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点
disqus: #shortname

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
gitalk:
  clientID: 1ec73fc0fe4217877bdd
  clientSecret: 33091b7f3b94430328e66a24872a761959184991
  repo: YancyLi1117.github.io
  owner: YancyLi1117
  proxy:

# 输入Google Analytics web tracking code
google_analytics:

utteranc:
  repo: # Your github repo path, also see: https://utteranc.es

#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

